name: Deploy Frontend

on:
  push:
    branches:
      - frontend-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Sync frontend files to server
        run: |
          rsync -avz --delete -e "ssh -p ${{ secrets.SERVER_PORT }}" ./cli/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/var/www/portfolio/cli/

      - name: Restart frontend container
        run: |
          ssh -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd /var/www/portfolio
            docker compose build frontend
            docker compose up -d frontend
          EOF
