name: Deploy Frontend (Next.js + Docker)

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: SSH and Deploy via Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            echo "🚀 Starting frontend deployment..."

            cd /var/www/portfolio

            echo "🧹 Removing old frontend code..."
            rm -rf cli
            mkdir -p cli

            echo "⬇️ Cloning latest frontend code..."
            git clone --depth 1 https://github.com/mhmdalisadat/portfo.git cli || { echo "❌ Git clone failed"; exit 1; }

            echo "🐳 Building Docker container for frontend..."
            docker compose build frontend || { echo "❌ Docker build failed"; exit 1; }

            echo "🔁 Restarting frontend container..."
            docker compose up -d frontend || { echo "❌ Docker up failed"; exit 1; }

            echo "✅ Frontend deployed successfully via Docker Compose!"
